### ISSUE TITLE
Encountered 404 when accessing /api/products/:id/related(.:format)

### ISSUE THREAD

**Issue by zhuwu** [solidusio-contrib/solidus_related_products#12]
After this gem is installed, there is such an entry in the `rake routs` result:

```
related_api_product GET  /api/products/:id/related(.:format)  spree/api/products#related {:format=>"json"}
```

However, there is no such an action called `related` in `Spree::Api::ProductsController`. Thus, this URL always responses 404.

**Comment by graygilmore** [comment]
The gem itself creates the `#related` action: https://github.com/solidusio-contrib/solidus_related_products/blob/master/app/controllers/spree/admin/products_controller_decorator.rb#L4

Can I see the code you are trying to use to hit the endpoint?

**Comment by zhuwu** [comment]
I was referring to `/api/products/:id/related` instead of `/admin/products/:id/related`. There is an action for `/admin/products/:id/related`, but there is no action for `/api/products/:id/related`.
