### ISSUE TITLE
Backend selector disappeared after PR merged

### ISSUE THREAD

**Issue by brchristian** [solidusio-contrib/solidus_related_products#32]
After #29 was merged, our backend view went from this:

<img width="1168" alt="screen shot 2018-06-20 at 9 59 32 pm" src="https://user-images.githubusercontent.com/2460418/41684560-aad7035a-74d5-11e8-96bc-f0197f86a106.png">

To this:

<img width="1161" alt="screen shot 2018-06-20 at 10 00 04 pm" src="https://user-images.githubusercontent.com/2460418/41684563-ad70306e-74d5-11e8-9cec-77664926b546.png">

Note that the selector field does not display, so we can no longer add relations between products.

Are we missing something else we need to do other than pulling these commits? I don’t know enough about #29 to know offhand why this functionality would be broken.

(We’re running Solidus 2.4 if that’s helpful.)

**Comment by brchristian** [comment]
@Gamabunta94 are we missing something?

**Comment by kennyadsl** [comment]
@vassalloandrea do you have any suggestion here?

**Comment by vassalloandrea** [comment]
Hi @brchristian, yes. I think you need to run the `add_javascripts` install generator which adds the missing javascript files to the project: https://github.com/solidusio-contrib/solidus_related_products/pull/29/files#diff-d92b8ffb4455c12471c0c00299454620

**Comment by brchristian** [comment]
Hi @vassalloandrea thanks for the heads up! Re-running `bundle exec rails g solidus_related_products:install` appears to have done the trick. I’ll go ahead and close this issue. Thanks for your help! 👍
