### ISSUE TITLE
has_related_products? always returns true

### ISSUE THREAD

**Issue by octave** [solidusio-contrib/solidus_related_products#34]
`product.has_related_products?('accessories')` always returns true as soon as the relation type `accessories` has been created. I doesn't check that there are products associated to it. I'm using solidus 2.6.0.

**Comment by ChristianRimondi** [comment]
I think that is the way it is supposed to be. You can check if there are products associated to it by calling `product.accessories.any?`. However, I agree with you that the name `has_related_products?` is misleading.
