### ISSUE TITLE
Relationships are not destroyed when a product is removed

### ISSUE THREAD

**Issue by Draiken** [solidusio-contrib/solidus_related_products#36]
We removed a few products and discovered some errors caused by nil `related_to` items. I believe the relationships from a product should be removed together with the parent record.

Is there any particular reason we don't have this on the `Relation` model?
If not, I can provide a PR to fix it.

**Comment by Draiken** [comment]
Ok, I've just looked at the code (probably should have done that first), but it should be doing that. Maybe this has to do with the new gem that deals with deletion on Solidus?

I'll see if I can reproduce it

**Comment by spaghetticode** [comment]
Now that the PR has been merged I think this issue can be closed.

**Comment by aitbw** [comment]
Closed via #37
