### ISSUE TITLE
Not possible to configure relations between variants

### ISSUE THREAD

**Issue by hapax94** [solidusio-contrib/solidus_related_products#7]
I tried to configure a relation between a master product "Rails Jr Spaghetti" to a variant product "RoR t-ringer shirt (in blue)". See screenshot. It works but the "related_to" product is the master product, not the variant (in blue).
Il tried also to define a relation_type "Spree:variant" instead of "Spree:product", but it does not appear in the list of available relation_types when defining the relation.
I wonder if this extension works only with master products, but not variants.

![related products with variant](https://cloud.githubusercontent.com/assets/9320883/15159922/1d3e863c-16c5-11e6-96bb-52e571d696c7.png)

**Comment by ChristianRimondi** [comment]
Closed via #29 and #51
