### ISSUE TITLE
New rubygems release?

### ISSUE THREAD

**Issue by brchristian** [solidusio-contrib/solidus_related_products#80]
I notice that the last rubygems release of this extension was from 2016, and a lot has changed in the world of Solidus since then.

In fact, I cannot even install the most recent rubygems version!

If I create a brand new Ruby (2.6.6), Rails (5.1.7), Solidus (2.10.2), and solidus_related_products (1.1.0) application, I can’t run the migrations, as I get:

```
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateRelationTypes < ActiveRecord::Migration[4.2]
/[ruby_path]/ruby/2.6.6/gems/activerecord-5.1.7/lib/active_record/migration.rb:525:in `inherited'
/[app_path]/db/migrate/20200801224231_create_relation_types.solidus_related_products.rb:2:in `<top (required)>'
```

I suspect this can be fixed by simply cutting a newer version of the gem!

**Comment by aldesantis** [comment]
@brchristian thanks for noticing, we'll work on a new release on Friday!

**Comment by aldesantis** [comment]
@brchristian I think it makes sense for #79 to be fixed, what do you think?

**Comment by brchristian** [comment]
@aldesantis I'm not sure what's going on to cause #79! We are running the current github `master` in production so it's not affecting our production environment, but as I said in that issue, I wasn't able to get the current `master` working with a new store. So, not sure what might be going on there!

**Comment by aldesantis** [comment]
@brchristian I'll take a look to understand if it's an issue with the gem or the Solidus install so that we know we're not releasing a broken gem. 🙂
